# Generated by Django 5.0.6 on 2024-06-08 19:24

import django.core.validators
import flashcard_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(unique=True, validators=[flashcard_app.validators.validate_word])),
                ('native_translation', models.CharField(validators=[flashcard_app.validators.validate_word])),
                ('times_seen', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty_rating', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
