# Generated by Django 5.0.6 on 2024-06-08 19:28

import flashcard_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='foreign_word',
            field=models.CharField(validators=[flashcard_app.validators.validate_word]),
        ),
    ]
