# Generated by Django 5.0.6 on 2024-06-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_alter_flashcard_foreign_word'),
        ('user_profile_app', '0007_userprofile_target_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user_id',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile_app.userprofile'),
            preserve_default=False,
        ),
    ]
