# Generated by Django 5.0.6 on 2024-06-08 18:05

import user_profile_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0003_alter_userprofile_active_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=255, unique=True, validators=[user_profile_app.validators.validate_name]),
        ),
    ]
