# Generated by Django 5.0.6 on 2024-06-08 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0004_alter_userprofile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='words_learned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
