# Generated by Django 5.0.6 on 2024-06-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_language_app', '0003_remove_targetlanguage_user_id_and_more'),
        ('user_profile_app', '0006_alter_userprofile_active_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='target_language_app.targetlanguage'),
        ),
    ]
