# Generated by Django 5.0.6 on 2024-06-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile_app', '0006_alter_userprofile_active_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(default='Spanish', unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile_app.userprofile')),
            ],
        ),
    ]
