# Generated by Django 5.0.6 on 2024-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_language_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlanguage',
            name='language_name',
            field=models.CharField(default='Spanish'),
        ),
    ]
