# Generated by Django 5.0.6 on 2024-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_language_app', '0002_alter_targetlanguage_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetlanguage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='targetlanguage',
            name='flag_string_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
