# Generated by Django 5.0.6 on 2024-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_language_app', '0003_remove_targetlanguage_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlanguage',
            name='language_name',
            field=models.CharField(default='Spanish', unique=True),
        ),
    ]
